version: '2.0'

services:
#  nginx:
#    image: jinx
#    ports:
#      - 443:443
#    restart: always
#    depends_on:
#      - service

  proxy:
    image: traefik
    command: --configFile=/var/traefik/traefik.toml
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081" # traefik UI
    volumes:
      - ./traefik:/var/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gateway
      - service

  gateway:
    image: gateway
    ports:
      - 9000:9000
    depends_on:
      - service

  service:
    image: service
    ports:
      - 8080:8080

