version: '2.0'

services:
#  nginx:
#    image: jinx
#    ports:
#      - 443:443
#    restart: always
#    depends_on:
#      - service

  gateway:
    image: gateway
    ports:
      - 443:443
    depends_on:
      - service

  service:
    image: service
    ports:
      - 8080:8080

