version: '2.0'

services:
#  nginx:
#    image: jinx
#    ports:
#      - 443:443
#    restart: always
#    depends_on:
#      - service

  proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"     #The HTTP port
      - "8081:8081" #The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Traefik can listen to the Docker events

  gateway:
    image: gateway
    ports:
      - 9000:9000
    labels:
      - "traefik.frontend.rule=Host:gateway.local"  # should redirect rq based on header
    depends_on:
      - service

  service:
    image: service
    labels:
      - "traefik.frontend.rule=Host:service.local"  # should redirect rq based on header
    ports:
      - 8080:8080

