spring:
  application.name: uploader
  http.multipart:
    max-file-size: 100MB
    max-request-size: 100MB


server:
  port: 9000
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: undertow
    key-password: undertow
  undertow:
    accesslog:
      enabled: true
      dir: /tmp
    buffer-size: 16000
    buffers-per-region: 20
    direct-buffers: true
    io-threads: 4
    worker-threads: 32

zuul:
  routes:
    uploader: # spring.application.name value of service
      url: http://service:8080

ribbon.eureka.enabled: false
